"""
utils/email_attachments.py
--------------------------
Helpers for normalizing email attachments into a transport-agnostic format.

Both SMTP (email.mime) and SendGrid (base64 in JSON) need different
shapes; this module produces a single dict format and lets the senders
encode it however they need.

Standard attachment dict shape:
    {
        "filename": "Quote_2026-05-27.pdf",
        "content": <bytes>,                # raw file content
        "content_type": "application/pdf", # MIME type
    }

Public API:
    - make_attachment(filename, content, content_type=...)
    - normalize_attachments(items) -> list of standard dicts
    - validate_attachments(items) -> (is_valid, error_message)

Constraints:
    MAX_TOTAL_SIZE  = 25 MB (matches Gmail/Outlook)
    MAX_FILE_COUNT  = 10
    BLOCKED_EXT     = executable extensions blocked for safety
"""
from __future__ import annotations

import mimetypes
from pathlib import Path
from typing import Iterable, Union

from utils.logger import get_logger

logger = get_logger("email_attachments")

# ---------------------------------------------------------------------------
# Limits and policy
# ---------------------------------------------------------------------------
MAX_TOTAL_SIZE_BYTES = 25 * 1024 * 1024  # 25 MB
MAX_FILE_COUNT = 10

# Block executable / risky file types from being attached
_BLOCKED_EXTENSIONS = frozenset({
    ".exe", ".bat", ".cmd", ".com", ".scr", ".pif",
    ".msi", ".dll", ".vbs", ".js", ".jar", ".ps1",
})

_DEFAULT_CONTENT_TYPE = "application/octet-stream"


# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------
# An attachment input can be:
#   - dict with at least 'filename' and 'content' keys
#   - tuple of (filename, content_bytes)
#   - tuple of (filename, content_bytes, content_type)
#   - Path or str (file path; filename and type inferred)
AttachmentInput = Union[dict, tuple, Path, str]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def make_attachment(
    filename: str,
    content: bytes,
    content_type: str | None = None,
) -> dict:
    """
    Build a standard attachment dict from raw bytes.

    Used by callers that already have file contents in memory (e.g. PDFs
    generated by fpdf2 returning bytes).

    Args:
        filename: Display name in the email (e.g. "Quote_2026-05-27.pdf")
        content: Raw file bytes
        content_type: MIME type. If None, inferred from filename extension.

    Returns:
        Standardized attachment dict.

    Raises:
        ValueError: if content is empty or filename is invalid.
    """
    if not isinstance(content, (bytes, bytearray)):
        raise ValueError(f"Attachment content must be bytes, got {type(content)}")
    if not content:
        raise ValueError("Attachment content cannot be empty")
    if not filename or not isinstance(filename, str):
        raise ValueError("Attachment filename must be a non-empty string")

    safe_name = _sanitize_filename(filename)
    ctype = content_type or _guess_content_type(safe_name)

    return {
        "filename": safe_name,
        "content": bytes(content),
        "content_type": ctype,
    }


def normalize_attachments(items: Iterable[AttachmentInput] | None) -> list[dict]:
    """
    Convert a heterogeneous iterable of attachment inputs into the standard
    list-of-dicts format. Skips invalid entries with a warning rather than
    failing the whole send.

    Accepts:
        - None / empty list  -> returns []
        - list of standard dicts -> passes through (after re-validation)
        - list of (filename, bytes) tuples
        - list of (filename, bytes, content_type) tuples
        - list of Path / str (file paths to read from disk)
    """
    if not items:
        return []

    out: list[dict] = []
    for idx, item in enumerate(items):
        try:
            if isinstance(item, dict):
                out.append(make_attachment(
                    filename=item.get("filename") or item.get("name", ""),
                    content=item.get("content") or item.get("data", b""),
                    content_type=item.get("content_type"),
                ))
            elif isinstance(item, (Path, str)):
                path = Path(item)
                if not path.is_file():
                    logger.warning("Attachment path not found: %s", path)
                    continue
                out.append(make_attachment(
                    filename=path.name,
                    content=path.read_bytes(),
                ))
            elif isinstance(item, tuple) and len(item) >= 2:
                filename, content = item[0], item[1]
                ctype = item[2] if len(item) >= 3 else None
                out.append(make_attachment(filename, content, ctype))
            else:
                logger.warning("Unsupported attachment type at index %d: %r",
                               idx, type(item))
        except (ValueError, OSError) as e:
            logger.warning("Skipping invalid attachment at index %d: %s", idx, e)

    return out


def validate_attachments(attachments: list[dict]) -> tuple[bool, str]:
    """
    Validate a normalized attachment list against policy.

    Returns (is_valid, error_message).
    Empty list is always valid (no attachments).
    """
    if not attachments:
        return True, ""

    if len(attachments) > MAX_FILE_COUNT:
        return False, (
            f"附件数量超限：最多 {MAX_FILE_COUNT} 个，"
            f"当前 {len(attachments)} 个"
        )

    total = 0
    for att in attachments:
        ext = Path(att["filename"]).suffix.lower()
        if ext in _BLOCKED_EXTENSIONS:
            return False, f"出于安全考虑，禁止发送 {ext} 类型附件: {att['filename']}"
        total += len(att["content"])

    if total > MAX_TOTAL_SIZE_BYTES:
        mb_total = total / (1024 * 1024)
        return False, (
            f"附件总大小超限：{mb_total:.1f}MB > "
            f"{MAX_TOTAL_SIZE_BYTES // (1024 * 1024)}MB"
        )

    return True, ""


def attachment_summary(attachments: list[dict]) -> str:
    """Return a short human-readable summary for UI display."""
    if not attachments:
        return "无附件"
    total = sum(len(a["content"]) for a in attachments)
    kb = total / 1024
    if kb < 1024:
        size_str = f"{kb:.1f} KB"
    else:
        size_str = f"{kb / 1024:.1f} MB"
    names = ", ".join(a["filename"] for a in attachments[:3])
    if len(attachments) > 3:
        names += f" 等 {len(attachments)} 个"
    return f"{names} ({size_str})"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _sanitize_filename(name: str) -> str:
    """
    Strip directory components and dangerous chars from a filename.

    Keeps unicode (CJK is fine in attachment names per RFC 2231).
    """
    # Take only the basename - never trust caller-supplied paths
    safe = Path(name).name
    # Replace control chars and a few problematic characters
    safe = "".join(
        c if c.isprintable() and c not in '\\/:*?"<>|\r\n\t' else "_"
        for c in safe
    )
    return safe.strip() or "attachment"


def _guess_content_type(filename: str) -> str:
    """Guess MIME type from filename, with sensible defaults for trade docs."""
    ctype, _ = mimetypes.guess_type(filename)
    if ctype:
        return ctype

    ext = Path(filename).suffix.lower()
    fallbacks = {
        ".pdf": "application/pdf",
        ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        ".xls": "application/vnd.ms-excel",
        ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        ".doc": "application/msword",
        ".csv": "text/csv",
        ".txt": "text/plain",
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
    }
    return fallbacks.get(ext, _DEFAULT_CONTENT_TYPE)
