"""
utils/packing_invoice_pdf.py
-----------------------------
Packing List & Commercial Invoice PDF generator for international trade.

Generates professional PDF documents:
- Packing List: detailed carton-by-carton breakdown
- Commercial Invoice: formal trade invoice with HS codes
"""

from __future__ import annotations

import datetime
import os

from fpdf import FPDF

from utils.logger import get_logger

logger = get_logger("packing_invoice_pdf")

# ---------------------------------------------------------------------------
# Font setup (shared with pdf_gen.py)
# ---------------------------------------------------------------------------
_BASE_DIR = os.path.dirname(os.path.abspath(__file__))
_FONT_DIR = os.path.join(_BASE_DIR, "..", "fonts")
_NOTO_PATH = os.path.join(_FONT_DIR, "NotoSansSC-Regular.ttf")


def _setup_font(pdf: FPDF) -> str:
    """Register font and return font name."""
    if os.path.exists(_NOTO_PATH):
        try:
            pdf.add_font("NotoSans", "", _NOTO_PATH, uni=True)
            return "NotoSans"
        except Exception:
            pass
    try:
        from fpdf.fonts import FPDF_FONT_DIR
        dejavu = os.path.join(FPDF_FONT_DIR, "DejaVuSans.ttf")
        if os.path.exists(dejavu):
            pdf.add_font("DejaVu", "", dejavu, uni=True)
            return "DejaVu"
    except Exception:
        pass
    return "Arial"


# ---------------------------------------------------------------------------
# PDF Classes
# ---------------------------------------------------------------------------
class PackingListPDF(FPDF):
    def __init__(self, font_name: str = "Arial", title: str = "PACKING LIST"):
        super().__init__()
        self._font_name = font_name
        self._title = title

    def header(self):
        self.set_fill_color(30, 58, 95)
        self.rect(0, 0, 210, 18, "F")
        self.set_text_color(255, 255, 255)
        self.set_font(self._font_name, "B", 14)
        self.set_y(3)
        self.cell(0, 12, self._title, 0, 0, "C")
        self.set_text_color(0, 0, 0)
        self.ln(18)

    def footer(self):
        self.set_y(-13)
        self.set_fill_color(243, 244, 246)
        self.rect(0, self.get_y(), 210, 13, "F")
        self.set_font(self._font_name, "I", 8)
        self.set_text_color(107, 114, 128)
        self.cell(0, 10, f"Page {self.page_no()}  |  Generated by TradeAI Pro", 0, 0, "C")
        self.set_text_color(0, 0, 0)


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------
def _section_header(pdf: FPDF, font_name: str, title: str) -> None:
    pdf.set_fill_color(239, 246, 255)
    pdf.set_font(font_name, "B", 11)
    pdf.set_text_color(30, 58, 95)
    pdf.cell(0, 8, f"  {title}", 0, 1, "L", fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1)


def _info_row(pdf: FPDF, font_name: str, label: str, value: str) -> None:
    pdf.set_font(font_name, "B", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(45, 7, label, 0, 0, "L")
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 7, str(value) if value else "—", 0, 1, "L")
    pdf.set_text_color(0, 0, 0)


# ---------------------------------------------------------------------------
# Packing List PDF
# ---------------------------------------------------------------------------
def generate_packing_list_pdf(
    items: list[dict],
    shipper: dict,
    consignee: dict,
    shipping_info: dict,
) -> bytes:
    """
    Generate a Packing List PDF.

    Args:
        items: list of dicts with keys:
            - product, model, quantity, cartons, net_weight_kg,
              gross_weight_kg, carton_dims (LxWxH cm), cbm_per_carton
        shipper: dict with company, contact, address, phone
        consignee: dict with company, contact, address
        shipping_info: dict with invoice_no, date, port_of_loading,
                       port_of_discharge, vessel, marks

    Returns:
        PDF bytes
    """
    logger.info("Generating packing list: %d items", len(items))

    pdf = PackingListPDF(title="PACKING LIST")
    font_name = _setup_font(pdf)
    pdf._font_name = font_name
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=18)

    # Date & Invoice No
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(107, 114, 128)
    inv_no = shipping_info.get("invoice_no", "PL-001")
    inv_date = shipping_info.get("date", datetime.datetime.now().strftime("%Y-%m-%d"))
    pdf.cell(0, 6, f"No: {inv_no}    Date: {inv_date}", 0, 1, "R")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    # Shipper & Consignee
    col_w = 95
    _section_header(pdf, font_name, "Shipper & Consignee")
    pdf.set_font(font_name, "B", 9)
    pdf.cell(col_w, 6, "SHIPPER:", 0, 0, "L")
    pdf.cell(col_w, 6, "CONSIGNEE:", 0, 1, "L")
    pdf.set_font(font_name, "", 9)
    pdf.cell(col_w, 5, shipper.get("company", ""), 0, 0, "L")
    pdf.cell(col_w, 5, consignee.get("company", ""), 0, 1, "L")
    pdf.cell(col_w, 5, shipper.get("address", ""), 0, 0, "L")
    pdf.cell(col_w, 5, consignee.get("address", ""), 0, 1, "L")
    pdf.cell(col_w, 5, shipper.get("phone", ""), 0, 0, "L")
    pdf.cell(col_w, 5, consignee.get("contact", ""), 0, 1, "L")
    pdf.ln(4)

    # Shipping details
    _section_header(pdf, font_name, "Shipping Details")
    _info_row(pdf, font_name, "Port of Loading:", shipping_info.get("port_of_loading", ""))
    _info_row(pdf, font_name, "Port of Discharge:", shipping_info.get("port_of_discharge", ""))
    _info_row(pdf, font_name, "Vessel/Voyage:", shipping_info.get("vessel", ""))
    _info_row(pdf, font_name, "Marks & Numbers:", shipping_info.get("marks", "N/M"))
    pdf.ln(3)

    # Items table
    _section_header(pdf, font_name, "Packing Details")
    COL = [50, 25, 18, 18, 22, 22, 20, 15]
    HEADERS = ["Product", "Model", "Qty", "Ctns", "N.W.(kg)", "G.W.(kg)", "Dims(cm)", "CBM"]

    pdf.set_fill_color(30, 58, 95)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(font_name, "B", 8)
    for w, h in zip(COL, HEADERS):
        pdf.cell(w, 7, h, 0, 0, "C", fill=True)
    pdf.ln()
    pdf.set_text_color(0, 0, 0)

    total_cartons = 0
    total_nw = 0.0
    total_gw = 0.0
    total_cbm = 0.0
    fill = False

    for item in items:
        pdf.set_fill_color(248, 250, 252) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.set_font(font_name, "", 8)

        ctns = int(item.get("cartons", 0))
        nw = float(item.get("net_weight_kg", 0))
        gw = float(item.get("gross_weight_kg", 0))
        cbm = float(item.get("cbm_per_carton", 0)) * ctns

        total_cartons += ctns
        total_nw += nw
        total_gw += gw
        total_cbm += cbm

        row = [
            str(item.get("product", ""))[:25],
            str(item.get("model", ""))[:12],
            str(item.get("quantity", "")),
            str(ctns),
            f"{nw:.1f}",
            f"{gw:.1f}",
            str(item.get("carton_dims", "")),
            f"{cbm:.3f}",
        ]
        for w, val in zip(COL, row):
            pdf.cell(w, 6, val, 0, 0, "C", fill=True)
        pdf.ln()
        fill = not fill

    # Totals row
    pdf.set_fill_color(30, 58, 95)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(font_name, "B", 9)
    pdf.cell(COL[0] + COL[1] + COL[2], 7, "  TOTAL", 0, 0, "L", fill=True)
    pdf.cell(COL[3], 7, str(total_cartons), 0, 0, "C", fill=True)
    pdf.cell(COL[4], 7, f"{total_nw:.1f}", 0, 0, "C", fill=True)
    pdf.cell(COL[5], 7, f"{total_gw:.1f}", 0, 0, "C", fill=True)
    pdf.cell(COL[6], 7, "", 0, 0, "C", fill=True)
    pdf.cell(COL[7], 7, f"{total_cbm:.3f}", 0, 0, "C", fill=True)
    pdf.ln()
    pdf.set_text_color(0, 0, 0)

    result = bytes(pdf.output())
    logger.info("Packing list PDF generated: %d bytes", len(result))
    return result


# ---------------------------------------------------------------------------
# Commercial Invoice PDF
# ---------------------------------------------------------------------------
def generate_commercial_invoice_pdf(
    items: list[dict],
    seller: dict,
    buyer: dict,
    trade_terms: dict,
) -> bytes:
    """
    Generate a Commercial Invoice PDF.

    Args:
        items: list of dicts with keys:
            - product, hs_code, quantity, unit, unit_price, amount, origin
        seller: dict with company, address, phone, bank_info
        buyer: dict with company, address, contact
        trade_terms: dict with invoice_no, date, payment_terms,
                     trade_term (FOB/CIF/etc), currency, port

    Returns:
        PDF bytes
    """
    logger.info("Generating commercial invoice: %d items", len(items))

    pdf = PackingListPDF(title="COMMERCIAL INVOICE")
    font_name = _setup_font(pdf)
    pdf._font_name = font_name
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=18)

    # Invoice header
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(107, 114, 128)
    inv_no = trade_terms.get("invoice_no", "CI-001")
    inv_date = trade_terms.get("date", datetime.datetime.now().strftime("%Y-%m-%d"))
    pdf.cell(0, 6, f"Invoice No: {inv_no}    Date: {inv_date}", 0, 1, "R")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    # Seller & Buyer
    col_w = 95
    _section_header(pdf, font_name, "Parties")
    pdf.set_font(font_name, "B", 9)
    pdf.cell(col_w, 6, "SELLER:", 0, 0, "L")
    pdf.cell(col_w, 6, "BUYER:", 0, 1, "L")
    pdf.set_font(font_name, "", 9)
    pdf.cell(col_w, 5, seller.get("company", ""), 0, 0, "L")
    pdf.cell(col_w, 5, buyer.get("company", ""), 0, 1, "L")
    pdf.cell(col_w, 5, seller.get("address", ""), 0, 0, "L")
    pdf.cell(col_w, 5, buyer.get("address", ""), 0, 1, "L")
    pdf.cell(col_w, 5, seller.get("phone", ""), 0, 0, "L")
    pdf.cell(col_w, 5, buyer.get("contact", ""), 0, 1, "L")
    pdf.ln(4)

    # Trade terms
    _section_header(pdf, font_name, "Terms of Sale")
    currency = trade_terms.get("currency", "USD")
    _info_row(pdf, font_name, "Payment Terms:", trade_terms.get("payment_terms", ""))
    _info_row(pdf, font_name, "Trade Term:", trade_terms.get("trade_term", "FOB"))
    _info_row(pdf, font_name, "Currency:", currency)
    _info_row(pdf, font_name, "Port:", trade_terms.get("port", ""))
    pdf.ln(3)

    # Items table
    _section_header(pdf, font_name, "Invoice Details")
    COL = [45, 22, 20, 18, 25, 30, 30]
    HEADERS = ["Description", "HS Code", "Qty", "Unit", "Unit Price", "Amount", "Origin"]

    pdf.set_fill_color(30, 58, 95)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(font_name, "B", 8)
    for w, h in zip(COL, HEADERS):
        pdf.cell(w, 7, h, 0, 0, "C", fill=True)
    pdf.ln()
    pdf.set_text_color(0, 0, 0)

    grand_total = 0.0
    fill = False

    for item in items:
        pdf.set_fill_color(248, 250, 252) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.set_font(font_name, "", 8)

        amount = float(item.get("amount", 0))
        grand_total += amount

        row = [
            str(item.get("product", ""))[:22],
            str(item.get("hs_code", "")),
            str(item.get("quantity", "")),
            str(item.get("unit", "PCS")),
            f"{currency} {float(item.get('unit_price', 0)):.2f}",
            f"{currency} {amount:,.2f}",
            str(item.get("origin", "China")),
        ]
        for w, val in zip(COL, row):
            pdf.cell(w, 6, val, 0, 0, "C", fill=True)
        pdf.ln()
        fill = not fill

    # Total row
    pdf.set_fill_color(30, 58, 95)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(font_name, "B", 9)
    total_label_w = sum(COL[:-2])
    pdf.cell(total_label_w, 8, "  TOTAL", 0, 0, "L", fill=True)
    pdf.cell(COL[-2], 8, f"{currency} {grand_total:,.2f}", 0, 0, "C", fill=True)
    pdf.cell(COL[-1], 8, "", 0, 0, "C", fill=True)
    pdf.ln()
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # Bank info (if provided)
    bank_info = seller.get("bank_info", "")
    if bank_info:
        _section_header(pdf, font_name, "Bank Information")
        pdf.set_font(font_name, "", 9)
        pdf.multi_cell(0, 5, bank_info)
        pdf.ln(4)

    # Declaration
    pdf.set_font(font_name, "I", 8)
    pdf.set_text_color(107, 114, 128)
    pdf.multi_cell(
        0, 5,
        "We hereby certify that the above information is true and correct. "
        "The goods are of Chinese origin unless otherwise stated.",
    )
    pdf.ln(8)

    # Signature line
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(95, 6, "________________________", 0, 0, "C")
    pdf.cell(95, 6, "________________________", 0, 1, "C")
    pdf.set_font(font_name, "", 8)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(95, 5, "Authorized Signature (Seller)", 0, 0, "C")
    pdf.cell(95, 5, "Date", 0, 1, "C")

    result = bytes(pdf.output())
    logger.info("Commercial invoice PDF generated: %d bytes", len(result))
    return result



# ---------------------------------------------------------------------------
# Proforma Invoice PDF
# ---------------------------------------------------------------------------
def generate_proforma_invoice_pdf(
    items: list[dict],
    seller: dict,
    buyer: dict,
    trade_terms: dict,
) -> bytes:
    """
    Generate a Proforma Invoice PDF.

    Earlier stage than Commercial Invoice — used for price confirmation,
    customs pre-clearance, and securing Letters of Credit.

    Args:
        items: list of dicts with keys:
            - product, quantity, unit, unit_price, amount, description
        seller: dict with company, address, phone, bank_info
        buyer: dict with company, address, contact
        trade_terms: dict with proforma_no, date, payment_terms,
                     trade_term (FOB/CIF/etc), currency, port, validity,
                     delivery_time

    Returns:
        PDF bytes
    """
    logger.info("Generating proforma invoice: %d items", len(items))

    pdf = PackingListPDF(title="PROFORMA INVOICE")
    font_name = _setup_font(pdf)
    pdf._font_name = font_name
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=18)

    # Invoice header
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(107, 114, 128)
    pi_no = trade_terms.get("proforma_no", "PI-001")
    pi_date = trade_terms.get("date", datetime.datetime.now().strftime("%Y-%m-%d"))
    pdf.cell(0, 6, f"Proforma Invoice No: {pi_no}    Date: {pi_date}", 0, 1, "R")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    # Seller & Buyer
    col_w = 95
    _section_header(pdf, font_name, "Parties")
    pdf.set_font(font_name, "B", 9)
    pdf.cell(col_w, 6, "SELLER / EXPORTER:", 0, 0, "L")
    pdf.cell(col_w, 6, "BUYER / IMPORTER:", 0, 1, "L")
    pdf.set_font(font_name, "", 9)
    pdf.cell(col_w, 5, seller.get("company", ""), 0, 0, "L")
    pdf.cell(col_w, 5, buyer.get("company", ""), 0, 1, "L")
    pdf.cell(col_w, 5, seller.get("address", ""), 0, 0, "L")
    pdf.cell(col_w, 5, buyer.get("address", ""), 0, 1, "L")
    pdf.cell(col_w, 5, seller.get("phone", ""), 0, 0, "L")
    pdf.cell(col_w, 5, buyer.get("contact", ""), 0, 1, "L")
    pdf.ln(3)

    # Trade terms
    _section_header(pdf, font_name, "Terms & Conditions")
    currency = trade_terms.get("currency", "USD")
    tc1, tc2 = 95, 95
    pdf.set_font(font_name, "B", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(tc1 // 2, 6, "Payment Terms:", 0, 0)
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(tc1 // 2, 6, trade_terms.get("payment_terms", ""), 0, 0)
    pdf.set_font(font_name, "B", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(tc2 // 2, 6, "Trade Term:", 0, 0)
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(tc2 // 2, 6, trade_terms.get("trade_term", "FOB"), 0, 1)

    pdf.set_font(font_name, "B", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(tc1 // 2, 6, "Port of Shipment:", 0, 0)
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(tc1 // 2, 6, trade_terms.get("port", ""), 0, 0)
    pdf.set_font(font_name, "B", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(tc2 // 2, 6, "Delivery Time:", 0, 0)
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(tc2 // 2, 6, trade_terms.get("delivery_time", ""), 0, 1)

    pdf.set_font(font_name, "B", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(tc1 // 2, 6, "Validity:", 0, 0)
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(tc1 // 2, 6, trade_terms.get("validity", "30 days"), 0, 0)
    pdf.set_font(font_name, "B", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(tc2 // 2, 6, "Currency:", 0, 0)
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(tc2 // 2, 6, currency, 0, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # Items table
    _section_header(pdf, font_name, "Product Details")
    COL = [55, 20, 18, 30, 30, 37]
    HEADERS = ["Description", "Qty", "Unit", "Unit Price", "Amount", "Remarks"]

    pdf.set_fill_color(30, 58, 95)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(font_name, "B", 8)
    for w, h in zip(COL, HEADERS):
        pdf.cell(w, 7, h, 0, 0, "C", fill=True)
    pdf.ln()
    pdf.set_text_color(0, 0, 0)

    grand_total = 0.0
    fill = False

    for item in items:
        pdf.set_fill_color(248, 250, 252) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.set_font(font_name, "", 8)

        amount = float(item.get("amount", 0))
        grand_total += amount

        row = [
            str(item.get("product", ""))[:28],
            str(item.get("quantity", "")),
            str(item.get("unit", "PCS")),
            f"{currency} {float(item.get('unit_price', 0)):.2f}",
            f"{currency} {amount:,.2f}",
            str(item.get("description", ""))[:18],
        ]
        for w, val in zip(COL, row):
            pdf.cell(w, 6, val, 0, 0, "C", fill=True)
        pdf.ln()
        fill = not fill

    # Total row
    pdf.set_fill_color(30, 58, 95)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(font_name, "B", 9)
    total_w = sum(COL[:4])
    pdf.cell(total_w, 8, "  TOTAL AMOUNT", 0, 0, "L", fill=True)
    pdf.cell(COL[4], 8, f"{currency} {grand_total:,.2f}", 0, 0, "C", fill=True)
    pdf.cell(COL[5], 8, "", 0, 0, "C", fill=True)
    pdf.ln()
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # Bank info
    bank_info = seller.get("bank_info", "")
    if bank_info:
        _section_header(pdf, font_name, "Banking Details")
        pdf.set_font(font_name, "", 9)
        pdf.multi_cell(0, 5, bank_info)
        pdf.ln(4)

    # Acceptance clause
    _section_header(pdf, font_name, "Acceptance")
    pdf.set_font(font_name, "", 8)
    pdf.set_text_color(107, 114, 128)
    pdf.multi_cell(
        0, 5,
        "This proforma invoice is subject to the terms and conditions stated above. "
        "Please confirm your acceptance by signing and returning one copy. "
        "Prices are valid for the period stated."
    )
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)

    # Signature lines
    pdf.set_font(font_name, "", 9)
    pdf.cell(95, 6, "________________________", 0, 0, "C")
    pdf.cell(95, 6, "________________________", 0, 1, "C")
    pdf.set_font(font_name, "", 8)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(95, 5, "Authorized Signature (Seller)", 0, 0, "C")
    pdf.cell(95, 5, "Confirmed by Buyer / Date", 0, 1, "C")

    result = bytes(pdf.output())
    logger.info("Proforma invoice PDF generated: %d bytes", len(result))
    return result
