"""
utils/pdf_gen.py — 报价单 PDF 生成（支持多产品 SKU）

中文支持策略：
  优先使用 fpdf2 内置的 DejaVu Unicode 字体。
  若需要完整 CJK 支持，可在 /fonts/ 目录放置 NotoSansSC-Regular.ttf，
  程序会自动检测并优先使用。
"""

from __future__ import annotations

import datetime
import os

from fpdf import FPDF

# ---------------------------------------------------------------------------
# 字体配置
# ---------------------------------------------------------------------------
_BASE_DIR  = os.path.dirname(os.path.abspath(__file__))
_FONT_DIR  = os.path.join(_BASE_DIR, "..", "fonts")
_NOTO_PATH = os.path.join(_FONT_DIR, "NotoSansSC-Regular.ttf")


def _setup_font(pdf: FPDF) -> str:
    """
    注册字体并返回字体名称。
    优先级：NotoSansSC（完整CJK）> DejaVu（内置Unicode）> Arial（ASCII兜底）
    """
    if os.path.exists(_NOTO_PATH):
        try:
            pdf.add_font("NotoSans", "", _NOTO_PATH, uni=True)
            return "NotoSans"
        except Exception:
            pass

    # fpdf2 >= 2.7.6 内置 DejaVu
    try:
        from fpdf.fonts import FPDF_FONT_DIR  # type: ignore
        dejavu = os.path.join(FPDF_FONT_DIR, "DejaVuSans.ttf")
        if os.path.exists(dejavu):
            pdf.add_font("DejaVu", "", dejavu, uni=True)
            return "DejaVu"
    except Exception:
        pass

    return "Arial"


# ---------------------------------------------------------------------------
# PDF 类
# ---------------------------------------------------------------------------
class QuotePDF(FPDF):
    def __init__(self, font_name: str = "Arial", company: str = ""):
        super().__init__()
        self._font_name = font_name
        self._company   = company

    def header(self):
        # 渐变色装饰条（用矩形模拟）
        self.set_fill_color(30, 58, 95)
        self.rect(0, 0, 210, 18, "F")
        self.set_text_color(255, 255, 255)
        self.set_font(self._font_name, "B", 14)
        self.set_y(3)
        self.cell(0, 12, "QUOTATION", 0, 0, "C")
        if self._company:
            self.set_font(self._font_name, "", 8)
            self.set_y(3)
            self.cell(0, 12, self._company, 0, 0, "R")
        self.set_text_color(0, 0, 0)
        self.ln(18)

    def footer(self):
        self.set_y(-13)
        self.set_fill_color(243, 244, 246)
        self.rect(0, self.get_y(), 210, 13, "F")
        self.set_font(self._font_name, "I", 8)
        self.set_text_color(107, 114, 128)
        self.cell(0, 10, f"Page {self.page_no()}  |  Generated by TradeAI Pro", 0, 0, "C")
        self.set_text_color(0, 0, 0)


# ---------------------------------------------------------------------------
# 辅助：section 标题
# ---------------------------------------------------------------------------
def _section(pdf: FPDF, font_name: str, title: str) -> None:
    pdf.set_fill_color(239, 246, 255)
    pdf.set_font(font_name, "B", 11)
    pdf.set_text_color(30, 58, 95)
    pdf.cell(0, 8, f"  {title}", 0, 1, "L", fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(1)


def _truncate_by_width(pdf: FPDF, font_name: str, text: str, max_mm: float) -> str:
    """
    按渲染宽度截断字符串，避免 CJK/混合字符溢出。
    使用 fpdf2 的 get_string_width() 而非字符数，确保视觉宽度正确。
    """
    if not text:
        return text
    pdf.set_font(font_name, "", 9)
    if pdf.get_string_width(text) <= max_mm:
        return text
    # 逐字符缩减直到满足宽度
    ellipsis = "…"
    for i in range(len(text) - 1, 0, -1):
        candidate = text[:i] + ellipsis
        if pdf.get_string_width(candidate) <= max_mm:
            return candidate
    return ellipsis


def _row(pdf: FPDF, font_name: str, label: str, value: str,
         label_w: int = 45, row_h: int = 7) -> None:
    pdf.set_font(font_name, "B", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(label_w, row_h, label, 0, 0, "L")
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, row_h, str(value) if value else "—", 0, 1, "L")
    pdf.set_text_color(0, 0, 0)


# ---------------------------------------------------------------------------
# 主入口：支持多产品 SKU
# ---------------------------------------------------------------------------
def generate_quote_pdf(
    skus: list[dict],
    payment: str = "T/T 30%",
    delivery: str = "15-20 days",
    validity: str = "30 days",
    shipping: str = "",
    company_name: str = "[Your Company]",
    contact_name: str = "[Your Name]",
    email: str = "[email@example.com]",
    phone: str = "[+86-xxx-xxxxxxx]",
    buyer_company: str = "",
    buyer_contact: str = "",
    buyer_email: str = "",
) -> bytes:
    """
    生成多产品 PDF 报价单，返回字节流。

    skus: list of dict，每条包含 product / model / price / quantity / unit
    buyer_*: 可选的客户（收单方）信息
    """
    pdf = QuotePDF(company=company_name)
    font_name = _setup_font(pdf)
    pdf._font_name = font_name

    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=18)

    # ── 报价日期 ──────────────────────────────────────
    pdf.set_font(font_name, "", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(0, 6, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d')}", 0, 1, "R")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    # ── 产品明细表 ────────────────────────────────────
    _section(pdf, font_name, "Product Details")

    # 表头
    COL = [70, 35, 22, 22, 20, 21]  # 宽度列表
    HEADERS = ["Product Name", "Model/Spec", "Unit Price", "Qty", "Unit", "Amount"]
    pdf.set_fill_color(30, 58, 95)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(font_name, "B", 9)
    for w, h in zip(COL, HEADERS):
        pdf.cell(w, 8, h, 0, 0, "C", fill=True)
    pdf.ln()
    pdf.set_text_color(0, 0, 0)

    # 行数据
    grand_total = 0.0
    fill = False
    for sku in skus:
        name     = sku.get("product", "")
        model    = sku.get("model", "") or "—"
        price    = float(sku.get("price", 0))
        quantity = int(sku.get("quantity", 0))
        unit     = sku.get("unit", "PCS")
        amount   = price * quantity
        grand_total += amount

        # 截断过长文本防止溢出（按渲染宽度截断，兼容 CJK/混合字符）
        name  = _truncate_by_width(pdf, font_name, name,  max_mm=68)
        model = _truncate_by_width(pdf, font_name, model, max_mm=33)

        pdf.set_fill_color(248, 250, 252) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.set_font(font_name, "", 9)
        row_data = [
            name, model,
            f"${price:.2f}", str(quantity), unit,
            f"${amount:,.2f}",
        ]
        for w, val in zip(COL, row_data):
            pdf.cell(w, 7, val, 0, 0, "C" if w <= 35 else "L", fill=True)
        pdf.ln()
        fill = not fill

    # 合计行
    pdf.set_fill_color(30, 58, 95)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(font_name, "B", 10)
    total_label_w = sum(COL[:-1])
    pdf.cell(total_label_w, 9, "  GRAND TOTAL", 0, 0, "L", fill=True)
    pdf.cell(COL[-1], 9, f"${grand_total:,.2f}", 0, 1, "C", fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # ── 交易条款 ──────────────────────────────────────
    _section(pdf, font_name, "Trade Terms")
    _row(pdf, font_name, "Payment Terms:", payment)
    _row(pdf, font_name, "Delivery Time:", delivery)
    _row(pdf, font_name, "Validity:",      validity)
    _row(pdf, font_name, "Shipping Port:", shipping or "—")
    pdf.ln(4)

    # ── 客户信息（Buyer）──────────────────────────────
    if buyer_company or buyer_contact or buyer_email:
        _section(pdf, font_name, "Buyer Information")
        if buyer_company:
            _row(pdf, font_name, "Company:",  buyer_company)
        if buyer_contact:
            _row(pdf, font_name, "Contact:",  buyer_contact)
        if buyer_email:
            _row(pdf, font_name, "Email:",    buyer_email)
        pdf.ln(4)

    # ── 公司信息（Seller）────────────────────────────
    _section(pdf, font_name, "Seller Information")
    _row(pdf, font_name, "Company:",  company_name)
    _row(pdf, font_name, "Contact:",  contact_name)
    _row(pdf, font_name, "Email:",    email)
    _row(pdf, font_name, "Phone:",    phone)
    pdf.ln(6)

    # ── 免责声明 ──────────────────────────────────────
    pdf.set_font(font_name, "I", 8)
    pdf.set_text_color(156, 163, 175)
    pdf.multi_cell(
        0, 5,
        "This quotation is valid for the period stated above. Prices are subject to change "
        "without notice after the validity period. Thank you for your business!",
    )

    return bytes(pdf.output())
